apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: t4gcuf46h-python 
  janus-idp.io/tekton: t4gcuf46h-python
  backstage.io/kubernetes-id: t4gcuf46h-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: t4gcuf46h-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml